version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore: "
    labels:
      - "golang"
      - "dependencies"
    reviewers:
      - "block-wallet/backgroundreviewers"